name: ESP32 CI/CD

on:
  push:
    branches: [ actions ]
jobs:
    build:
        runs-on: ubuntu-latest
        container: espressif/idf:release-v4.4
        steps:
        - name: Pull Repo
          run: git clone https://github.com/vChavezB/qpcpp.git -b esp32
        - name: Build
          working-directory: qpcpp/examples/esp-idf/dpp-esp-idf
          run: |         
              . $IDF_PATH/export.sh
              idf.py build
              mkdir ~/build
              mv build/dpp.bin ~/build/dpp.bin
        - name: Upload binary
          uses: actions/upload-artifact@v3
          with:
            name: dpp-binary
            path: ~/build/dpp.bin
      
            
    Emulate:
        runs-on: ubuntu-latest
        container: mluis/qemu-esp32
        needs: build
        steps:
        - name: Download DPP binary
          uses: actions/download-artifact@v3
          with:
            name: dpp-binary
        - name: Run QEMU
          run: echo $(ls)
          
