name: ESP32 CI/CD

on:
  push:
    branches: [ actions ]
jobs:
    build:
        runs-on: ubuntu-latest
        container: espressif/idf
        steps:
        - name: Pull Repo
          run: | 
              git clone https://github.com/vChavezB/qpcpp.git -b esp32
              cd qpcpp/examples/esp-idf/dpp-esp-idf
        - name: read
          run: cat README.md
        - name: Set environment
          run: |         
              export IDF_PATH=/opt/esp/idf
              . $IDF_PATH/export.sh
              python $IDF_PATH/tools/idf.py build
