name: ESP32 CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        container: mluis/qemu-esp32
        steps:
        - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
        name: Run in container
