name: ESP32 CI/CD

on:
  push:
    branches: [ actions ]
jobs:
    build:
        runs-on: ubuntu-latest
        container: espressif/idf
        steps:
        - name: Build Example
          run: |
            git clone https://github.com/vChavezB/qpcpp.git -b esp32
            cd qpcpp/examples/esp-idf/dpp-esp-idf
            python idf.py build

