name: ESP32 CI/CD

on:
  push:
    branches: [ actions ]
jobs:
    build:
        runs-on: ubuntu-latest
        container: mluis/qemu-esp32
        steps:
        - name: Build Example
          run: |
            cd examples/esp-idf/dpp-esp-idf
            source /root/esp/esp-idf/export.sh
            make -j8

