name: ESP32 CI/CD

on:
  push:
    branches: [ actions ]
jobs:
    build:
        runs-on: ubuntu-latest
        container: espressif/idf:release-v4.1 
        steps:
        - name: Pull Repo
          run: git clone https://github.com/vChavezB/qpcpp.git -b esp32
        - name: Set environment
          working-directory: qpcpp/examples/esp-idf/dpp-esp-idf
          run: |         
              . $IDF_PATH/export.sh
              idf.py build
