name: ESP32 CI/CD

on:
  push:
    branches: [ actions ]
jobs:
    build:
        runs-on: ubuntu-latest
        container: mluis/qemu-esp32
        steps:
        - name: docker login
          run: |
            ls
