name: ESP32 CI/CD

on:
  push:
    branches: [ actions ]
jobs:
    build:
        runs-on: ubuntu-latest
        container: espressif/idf:release-v4.4
        steps:
        - name: Pull Repo
          run: git clone https://github.com/vChavezB/qpcpp.git -b esp32
        - name: Build
          working-directory: qpcpp/examples/esp-idf/dpp-esp-idf
          run: |         
              . $IDF_PATH/export.sh
              idf.py build
              mkdir ~/build
              mv build/dpp.bin ~/build/dpp.bin
        - name: Upload binary
          uses: actions/upload-artifact@v3
          with:
            name: dpp-binary
            path: ~/build/dpp.bin
      
            
    Emulate:
        runs-on: ubuntu-latest
        container: mluis/qemu-esp32
        needs: build
        steps:
        - name: Download DPP binary
          uses: actions/download-artifact@v3
          with:
            name: dpp-binary
        - name: Create Image
          run: |
              export APP_BIN=dpp.bin
              dd if=/dev/zero bs=1M count=4 of=./flash.bin
              dd if=./bootloader/bootloader.bin bs=1 count=$(stat -c%s ./bootloader/bootloader.bin) seek=$((16#1000)) conv=notrunc of=./flash.bin
              dd if=./partitions_singleapp.bin bs=1 count=$(stat -c%s ./partitions_singleapp.bin) seek=$((16#8000)) conv=notrunc of=./flash.bin
              dd if=$APP_BIN bs=1 count=$(stat -c%s $APP_BIN) seek=$((16#10000)) conv=notrunc of=./flash.bin
              ./flash.sh dpp.bin
          
